### ISSUE TITLE
can't play the mod

### ISSUE THREAD

**Issue by Nadaadizer9611** [gorodmi/shapez#1]
Hello
today I tried to play in your mod, but there is no way to download it through mindustry or try to download it with the name of the mod through github, put some other way to download the mod and please fix this problem.

**Comment by gorodmi** [comment]
bruh fr

**Comment by gorodmi** [comment]
https://github.com/gorodmi/shapez/actions

**Comment by gorodmi** [comment]
![image](https://user-images.githubusercontent.com/83781960/199066413-c8326dd4-3669-4c9e-93b9-57bd7fbbc5e2.png)
![image](https://user-images.githubusercontent.com/83781960/199066466-c83cf5c8-8c12-4afe-83fa-bf328aa5b3f9.png)
unpack zip
![image](https://user-images.githubusercontent.com/83781960/199066650-4218b00a-426d-4c3e-836d-09d6edeaf39d.png)
